### ISSUE TITLE
Podsumowanie

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#11]
- [x] Wyświetlenie wyniku gracza w punktach, premia za czas i suma #48
- [x] Wyświetlenie wyniku komputera w punktach (suma) #48
- [ ] Wyświetlenie rankingu w zależności od poziomu trudności i zaznaczone które miejsce zajął gracz
- [x] Przycisk "zagraj ponownie" (automatycznie zaczyna grę na tych samych ustawieniach) #49 
- [x] Przycisk "wróć do menu głównego" #50
