### ISSUE TITLE
Pobieranie pytań i odpowiedzi

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#4]
- [x] Pobieranie wszystkich danych z danej kategorii- przy wyborze kategorii na przykład https://swapi.dev/people  #14 
- [x] Przy każdym starcie aplikacji losowo wybieranych jest 10 pytań (obrazek) i 3 błędne odpowiedzi do każdego pytania #15 
- [x] Obrazek pobierany jest ze static/assets #16
