### ISSUE TITLE
Wyświetlenie pytań i odpowiedzi

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#5]
- [x] 1 pytanie w formie obrazka #16 
- [x]  Wyświetlanie odpowiedniego pytania dla kategorii np. "Who is the character?" #17 
- [x] 4 odpowiedzi możliwe- 1 poprawna- trzeba zaznaczyć 1 odpowiedź- nieaktywny przycisk "dalej" dopóki nie udzieli się odpowiedzi #19 #23 
- [x] Wyświetlenie numeru pytania #17
- [x] Licznik czasu- ile czasu pozostało do końca #44 
- [x] Możliwa jest zmiana wyboru odpowiedzi do momentu naciśnięcia przycisku "dalej" #18
- [x] Po naciśnięciu przycisku "dalej" poprawna odpowiedź będzie wyświetlana przez x sekund na zielono, a niepoprawna na czerwono, po czym następuje zmiana pytania 
- [x] W przypadku problemów z połączeniem się z API - poinformowanie użytkownika o błędzie- np. Spróbuj później
