### ISSUE TITLE
Liczenie punktów - tryb normal

### ISSUE THREAD

**Issue by Ania-Em** [CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz#6]
- [x] Liczba pytań- 10, w czasie 2 minut #45 #46
- [x] Za każdą poprawną odpowiedź 10 punktów, za każdą pozostałą z 2 minut sekundę czasu dodawany jest 1 punkt #39 
- [x] Wyświetlanie poprawnych odpowiedzi, błędnych odpowiedzi w stosunku do wszystkich pytań np. 3/7/10  #20 
- [x] Ilość wszystkich punktów do tej pory zdobytych #22 
- [x] W przypadku odpowiedzenie na wszystkie pytania przed upływem czasu quiz automatycznie się kończy i dodawana jest premia za pozostały czas #46
